<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Promise对象的方法</title>
</head>
<body>
	
</body>
<script>
	//如果异步操作抛出错误,状态就会变为rejected,当then中没有指定rejected状态的回调时就会调用catch方法指定的回调函数    如果运行中抛出错误,也会被catch方法捕获
	let p1=new Promise((resolve,reject)=>{
		reject('OK')
	});
	/*
	p1.then(data=>{
		console.log('success',data)
	},err=>{
		console.log('falided',err)
	})
	*/
	p1.then(data=>{
		console.log('success',data)
	})
	.catch(err=>{
		console.log('falided',err);
	})	
</script>
</html>